services:

    LSB\NotificationBundle\Form\NotificationType:
        tags:
            - {name: form.type}

    LSB\NotificationBundle\Form\NotificationAttachmentType:
        tags:
            - {name: form.type}

    LSB\NotificationBundle\Form\NotificationBlackListType:
        tags:
            - {name: form.type}

    LSB\NotificationBundle\Form\NotificationLogEntryType:
        tags:
            - {name: form.type}

    LSB\NotificationBundle\Form\NotificationRecipientType:
        tags:
            - {name: form.type}