services:

    LSB\NotificationBundle\Manager\NotificationAttachmentManager:
        arguments:
            "$objectManager": '@lsb_utility_object_manager'
            "$kernel": '@kernel'
            "$storage": '@vich_uploader.storage.file_system'

    LSB\NotificationBundle\Manager\NotificationBlackListManager:
        arguments:
            "$objectManager": '@lsb_utility_object_manager'

    LSB\NotificationBundle\Manager\NotificationLogEntryManager:
        arguments:
            "$objectManager": '@lsb_utility_object_manager'
            "$notificationManager": '@LSB\NotificationBundle\Manager\NotificationManager'
            "$parameterBag": '@parameter_bag'

    LSB\NotificationBundle\Manager\NotificationRecipientManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\NotificationBundle\Manager\NotificationManager:
        arguments:
            "$objectManager": '@lsb_utility_object_manager'
            "$kernel": '@kernel'
            "$translator": '@translator'
            "$requestStack": '@request_stack'
            "$notificationAttachmentManager": '@LSB\NotificationBundle\Manager\NotificationAttachmentManager'
            "$parameterBag": '@parameter_bag'
            '$eventDispatcher': '@event_dispatcher'
            '$languageManager': '@LSB\LocaleBundle\Manager\LanguageManager'
            '$notificationRecipientManager': '@LSB\NotificationBundle\Manager\NotificationRecipientManager'
            '$channelModuleInventory': '@LSB\NotificationBundle\Manager\ChannelModuleInventory'


    LSB\NotificationBundle\Manager\NotificationParser:
        arguments:
            - '@parameter_bag'
            - '@twig'

    LSB\NotificationBundle\Manager\ChannelModuleInventory: ~