<?php
declare(strict_types=1);

namespace LSB\NotificationBundle\DependencyInjection;

use LSB\UtilityBundle\DependencyInjection\BaseExtension;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader;

/**
 * This is the class that loads and manages your bundle configuration.
 *
 * @link http://symfony.com/doc/current/cookbook/bundles/extension.html
 */
class LSBNotificationExtension extends BaseExtension
{
    const CONFIG_PREFIX = 'lsb_notification';
    protected $dir = __DIR__;

    public function load(array $configs, ContainerBuilder $container)
    {
        parent::load($configs, $container); // TODO: Change the autogenerated stub

        $loader = new Loader\YamlFileLoader($container, new FileLocator($this->dir . '/../Resources/config'));
        $loader->load('channels.yml');
    }

    /**
     * @return ConfigurationInterface
     */
    public function getTreeConfiguration(): ConfigurationInterface
    {
        return new Configuration();
    }
}
